site_name: MAD
repo_url: https://github.com/fchauvel/mad
docs_dir: docs
pages:
 - "Home": index.md
 - "Installation": installation.md
 - "MAD Syntax":
   - "Example": syntax.md
   - "Queue": queue.md
   - "Autoscaling": autoscaling.md
   - "Throttling": throttling.md
   - "Service Differentiation": service_differentiation.md
   - "Actions": actions.md
theme: flatly